"""
CCAR Backtesting Agent — Gradio Web UI
=======================================
Single-tab chatbox UI with dataset selector and CSV-backed summary dashboard.

Summary dashboard reads from pre-computed CSV files generated by:
    python backtesting_agent/precompute_summary.py

Run UI with:
    python backtesting_agent/app.py
"""
from __future__ import annotations

import os
import sys
import glob
import time
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

_repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(_repo_root))
sys.path.insert(0, str(_repo_root / "src"))

import gradio as gr
from backtesting_agent.agent import build_agent, _load_config

# ── Paths ─────────────────────────────────────────────────────────────────────
SAMPLE_DIR     = Path(__file__).parent / "sample_data"
ROUND1_PATH    = str(SAMPLE_DIR / "ccar_round1.parquet")
ROUND2_PATH    = str(SAMPLE_DIR / "ccar_round2.parquet")
OUTPUT_DIR     = str(Path(__file__).parent.parent / "backtesting_output")
DATA_INPUT_DIR = Path(__file__).parent / "data_input"

# Timestamp updated on Clear — gallery only shows charts from the current session
_session_start_time: float = time.time()

# ── Build agent once at startup ───────────────────────────────────────────────
_PATH_HINT = f"""
Available sample data files (tell the user these paths if they ask):
  Round 1: {ROUND1_PATH}
  Round 2: {ROUND2_PATH}

IMPORTANT: Never call user_input() or input(). If a file path is not
specified by the user, ask them which dataset they want to use.
"""
agent = build_agent(extra_instructions=_PATH_HINT)


# ── Dataset choices from config ───────────────────────────────────────────────
def _get_dataset_choices() -> list[str]:
    cfg = _load_config()
    return list(cfg.get("datasets", {}).keys())


# ── CSV helpers ───────────────────────────────────────────────────────────────
def _csv_path(dataset_name: str) -> Path:
    return DATA_INPUT_DIR / f"{dataset_name}_summary.csv"


def _read_summary_csv(dataset_name: str) -> pd.DataFrame | None:
    p = _csv_path(dataset_name)
    if not p.exists():
        return None
    return pd.read_csv(p)


def _csv_missing_msg(dataset_name: str) -> str:
    return (
        f"Pre-computed summary CSV not found for **{dataset_name}**.\n\n"
        f"Please run:\n```\npython backtesting_agent/precompute_summary.py\n```"
    )


# ── Summary chart (MPE bar charts from CSV) ───────────────────────────────────
def generate_summary_charts(dataset_name: str):
    """Read pre-computed CSV and plot MPE bar charts — one subplot per target."""
    if not dataset_name:
        return None

    df = _read_summary_csv(dataset_name)
    if df is None:
        fig, ax = plt.subplots(figsize=(8, 2))
        ax.text(0.5, 0.5, _csv_missing_msg(dataset_name),
                transform=ax.transAxes, ha="center", va="center",
                fontsize=10, color="red", wrap=True)
        ax.axis("off")
        plt.tight_layout()
        return fig

    cfg     = _load_config()
    targets = cfg.get("target_variables", {})
    if not targets:
        return None

    n   = len(targets)
    fig, axes = plt.subplots(n, 1, figsize=(10, 5 * n))
    if n == 1:
        axes = [axes]

    MAX_HORIZONS = 28
    BAR_COLOR    = "#4c72b0"

    for ax, (target_name, tcols) in zip(axes, targets.items()):
        col_mpe  = f"{target_name}_mpe"
        mtype    = tcols.get("metric_type", "flow")
        agg_label = "sum" if mtype == "flow" else "avg"

        if col_mpe not in df.columns:
            ax.text(0.5, 0.5, f"Column '{col_mpe}' not found in CSV.\nRe-run precompute_summary.py.",
                    transform=ax.transAxes, ha="center", va="center", color="red")
            ax.set_title(target_name)
            continue

        complete   = df["max_horizon"] >= MAX_HORIZONS
        incomplete = ~complete

        labels = [str(d)[:7] for d in df["statement_month"]]
        x      = np.arange(len(labels))
        width  = 0.6

        if complete.any():
            ax.bar(x[complete], df.loc[complete, col_mpe], width,
                   color=BAR_COLOR, alpha=0.85, label="Complete (28 horizons)")
        if incomplete.any():
            ax.bar(x[incomplete], df.loc[incomplete, col_mpe], width,
                   color=BAR_COLOR, alpha=0.5, hatch="//",
                   label="Incomplete (< 28 horizons)")

        ax.axhline(y=0, color="black", linewidth=0.8, linestyle="--")
        step = max(1, len(labels) // 12)
        ax.set_xticks(x[::step])
        ax.set_xticklabels(labels[::step], rotation=45, ha="right", fontsize=8)
        ax.set_ylabel("MPE (%)")
        ax.set_title(
            f"{target_name} MPE by Statement Month\n"
            f"(Portfolio level, {agg_label} across horizons)",
            fontsize=10,
        )
        ax.legend(fontsize=7)
        ax.grid(True, alpha=0.3, axis="y")

    fig.suptitle(
        f"Dataset: {dataset_name} — Portfolio MPE by Statement Month",
        fontsize=13, y=1.01,
    )
    plt.tight_layout(rect=[0, 0, 1, 0.99])
    return fig


# ── Dashboard tables from CSV ─────────────────────────────────────────────────

def _build_avg_mpe_table(dataset_name: str) -> pd.DataFrame:
    """Average MPE and AMPE per target across all statement months."""
    df = _read_summary_csv(dataset_name)
    if df is None:
        return pd.DataFrame([{"Info": "Run precompute_summary.py first."}])
    cfg     = _load_config()
    targets = cfg.get("target_variables", {})
    rows = []
    for target_name in targets:
        col_mpe  = f"{target_name}_mpe"
        col_ampe = f"{target_name}_ampe"
        if col_mpe in df.columns:
            rows.append({
                "Target":    target_name,
                "Mean MPE":  f"{df[col_mpe].mean():+.2f}%",
                "Mean AMPE": f"{df[col_ampe].mean():.2f}%",
            })
    return pd.DataFrame(rows) if rows else pd.DataFrame([{"Info": "No data"}])


def _build_neg_pred_table(dataset_name: str) -> pd.DataFrame:
    """Statement months where any stock target has negative predicted portfolio value."""
    df = _read_summary_csv(dataset_name)
    if df is None:
        return pd.DataFrame([{"Info": "Run precompute_summary.py first."}])
    cfg     = _load_config()
    targets = cfg.get("target_variables", {})

    flag_cols = [f"{t}_pred_negative" for t, c in targets.items()
                 if c.get("metric_type") == "stock" and f"{t}_pred_negative" in df.columns]
    if not flag_cols:
        return pd.DataFrame([{"Info": "No stock targets with negative-prediction flag in CSV."}])

    mask = df[flag_cols].any(axis=1)
    neg  = df[mask][["statement_month"] + flag_cols].copy()
    if neg.empty:
        return pd.DataFrame([{"Info": "✅ No statement months with negative predicted values."}])

    # Rename flag columns for readability
    rename = {c: c.replace("_pred_negative", " < 0") for c in flag_cols}
    neg = neg.rename(columns=rename)
    neg["statement_month"] = neg["statement_month"].astype(str).str[:7]
    return neg.reset_index(drop=True)


def _build_ampe_flag_table(dataset_name: str, threshold: float = 5.0) -> pd.DataFrame:
    """Statement months where any target's AMPE exceeds the threshold (default 5%)."""
    df = _read_summary_csv(dataset_name)
    if df is None:
        return pd.DataFrame([{"Info": "Run precompute_summary.py first."}])
    cfg     = _load_config()
    targets = cfg.get("target_variables", {})

    rows = []
    for _, row in df.iterrows():
        flags = []
        for target_name in targets:
            col_ampe = f"{target_name}_ampe"
            if col_ampe in df.columns and pd.notna(row[col_ampe]) and row[col_ampe] > threshold:
                flags.append(f"{target_name}: {row[col_ampe]:.2f}%")
        if flags:
            rows.append({
                "Statement Month": str(row["statement_month"])[:7],
                f"AMPE > {threshold}%": ",  ".join(flags),
            })

    if not rows:
        return pd.DataFrame([{"Info": f"✅ No statement months with AMPE > {threshold}%."}])
    return pd.DataFrame(rows)


# ── Load all summary components at once ──────────────────────────────────────
def _load_summary(dataset_name: str) -> tuple:
    """Return (fig, avg_mpe_df, neg_pred_df, ampe_flag_df, chatbot_history)."""
    fig        = generate_summary_charts(dataset_name)
    avg_df     = _build_avg_mpe_table(dataset_name)
    neg_df     = _build_neg_pred_table(dataset_name)
    ampe_df    = _build_ampe_flag_table(dataset_name)
    msg        = (f"**Dataset: {dataset_name}** summary loaded. "
                  f"See the charts and tables on the left. "
                  f"Send a request below to start your analysis.")
    history    = [{"role": "assistant", "content": msg}]
    return fig, avg_df, neg_df, ampe_df, history


# ── Example prompts ───────────────────────────────────────────────────────────
EXAMPLES = [
    f"Inspect the file at '{ROUND1_PATH}' and summarise its schema.",
    f"Show me the Payment MPE trend by statement month at portfolio level using '{ROUND1_PATH}'.",
    f"Show me EOS actual vs predicted by horizon at portfolio level using '{ROUND1_PATH}'.",
    f"Show me PurchaseVolume AMPE by statement month at account level using '{ROUND1_PATH}'.",
    f"Compare Round 1 ('{ROUND1_PATH}') and Round 2 ('{ROUND2_PATH}') Payment MPE by horizon.",
]


# ── Chart gallery helpers ─────────────────────────────────────────────────────
def _collect_charts(since: float = 0.0) -> list[str]:
    pngs = glob.glob(os.path.join(OUTPUT_DIR, "**", "*.png"), recursive=True)
    if since:
        pngs = [p for p in pngs if os.path.getmtime(p) >= since]
    return sorted(pngs, key=os.path.getmtime, reverse=True)


def _session_charts() -> list[str]:
    return _collect_charts(since=_session_start_time)


# ── Confirmation detection ────────────────────────────────────────────────────
_CONFIRM_WORDS = {"yes", "y", "yes.", "yes!", "yep", "proceed", "go", "go ahead",
                  "ok", "okay", "sure", "correct", "confirmed", "confirm", "do it"}


def _is_confirmation(msg: str) -> bool:
    return msg.strip().lower().rstrip(".!") in _CONFIRM_WORDS


def _build_task(user_message: str, history: list) -> str:
    prior = history[:-1]
    if not prior:
        return user_message
    recent = prior[-6:]
    lines = ["Conversation so far (use this as full context for the request below):"]
    for msg in recent:
        role = "User" if msg["role"] == "user" else "Assistant"
        lines.append(f"  {role}: {msg['content']}")
    lines.append(f"\nUser's latest message: {user_message}")

    if _is_confirmation(user_message):
        plan_text = ""
        for m in reversed(prior):
            if m["role"] == "assistant" and "Here is my plan" in m.get("content", ""):
                plan_text = m["content"]
                break

        cfg     = _load_config()
        targets = cfg.get("target_variables", {})
        col_info = []
        for tname, tcols in targets.items():
            col_info.append(
                f"  {tname}: actual_column='{tcols.get('actual','')}', "
                f"predicted_column='{tcols.get('predicted','')}', "
                f"metric_type='{tcols.get('metric_type','flow')}'"
            )
        col_block = "\n".join(col_info) if col_info else "  (see config.yaml)"

        return (
            f"The user confirmed the plan below. Execute it NOW using the provided tools.\n\n"
            f"{plan_text}\n\n"
            f"EXACT COLUMN NAMES (from config.yaml — use these, do not guess):\n"
            f"{col_block}\n\n"
            f"MANDATORY EXECUTION STEPS — write these exact tool calls:\n"
            f"Step 1 (code block 1):\n"
            f"  result = aggregate_credit_card(\n"
            f"      file_path=<dataset path from plan>,\n"
            f"      actual_column=<actual_column from above>,\n"
            f"      predicted_column=<predicted_column from above>,\n"
            f"      metric_type=<metric_type from above>,\n"
            f"      dimension=<dimension from plan>,\n"
            f"      dataset_name='agg_result',\n"
            f"      level=<level from plan>,\n"
            f"      row_filter=<filter from plan or empty string>,\n"
            f"  )\n"
            f"  print(result)\n\n"
            f"Step 2 (code block 2):\n"
            f"  chart_path = plot_trend(\n"
            f"      x_column=<dimension column from plan>,\n"
            f"      y_columns='plot_actual,plot_predicted',\n"
            f"      dataset_name='agg_result',\n"
            f"      title=<descriptive title>,\n"
            f"      y_unit='millions',\n"
            f"  )\n"
            f"  print(chart_path)\n\n"
            f"Step 3: final_answer('Data source: <path>\\nChart saved to: <chart_path>')\n\n"
            f"RULES:\n"
            f"- Use ONLY aggregate_credit_card and plot_trend — do NOT write raw pandas or matplotlib code.\n"
            f"- Do NOT re-present the plan. Do NOT ask 'Shall I proceed?' again.\n"
            f"- Do NOT call final_answer() before Steps 1 and 2 are complete."
        )
    else:
        lines.append(
            "\nComplete the user's latest request using all context above. "
            "Do not ask again for clarifications already answered in the conversation. "
            "However, you MUST still follow the MANDATORY WORKFLOW: present the full "
            "execution plan and ask 'Shall I proceed? (yes/no)' before calling any tool, "
            "even if all information is already clear from context."
        )
    return "\n".join(lines)


# ── Visibility helpers ────────────────────────────────────────────────────────
_SUMMARY_COMPONENTS = 4   # summary_plot, avg_mpe_table, neg_pred_table, ampe_flag_table

def _hide_summary():
    return tuple(gr.update(visible=False) for _ in range(_SUMMARY_COMPONENTS))

def _show_summary(fig, avg_df, neg_df, ampe_df):
    return (
        gr.update(value=fig,     visible=True),
        gr.update(value=avg_df,  visible=True),
        gr.update(value=neg_df,  visible=True),
        gr.update(value=ampe_df, visible=True),
    )


# ── Agent runner ──────────────────────────────────────────────────────────────
def run_agent(user_message: str, history: list, dataset_name: str) -> tuple:
    """After first request: hide summary components, show gallery."""
    if not user_message.strip():
        return (history, "Enter a request above.",
                gr.update(), *[gr.update()] * _SUMMARY_COMPONENTS)

    history = history + [{"role": "user", "content": user_message}]

    charts_before = set(_collect_charts())
    task = _build_task(user_message, history)

    if _is_confirmation(user_message):
        try:
            agent.memory.reset()
        except Exception:
            pass

    try:
        result = agent.run(task)
    except Exception as e:
        result = f"ERROR: {e}"

    response   = str(result)
    new_charts = [c for c in _collect_charts() if c not in charts_before]
    if new_charts:
        new_names  = ", ".join(os.path.basename(c) for c in new_charts)
        response  += f"\n\n📊 New chart(s) generated: {new_names}"

    history = history + [{"role": "assistant", "content": response}]
    status  = (f"✅ Done — {len(new_charts)} new chart(s) generated."
               if new_charts else "✅ Done — no new charts.")

    return (history, status,
            gr.update(value=_session_charts(), visible=True),  # gallery: update value + show
            *_hide_summary())          # hide all summary components


def clear_all(dataset_name: str) -> tuple:
    """Reset session and restore summary dashboard."""
    global _session_start_time
    _session_start_time = time.time()
    try:
        agent.memory.reset()
    except Exception:
        pass
    fig, avg_df, neg_df, ampe_df, history = _load_summary(dataset_name)
    return (history, "Ready.",
            gr.update(value=[], visible=False),  # gallery: clear + hide
            *_show_summary(fig, avg_df, neg_df, ampe_df))


# ── Build the Gradio UI ───────────────────────────────────────────────────────
_dataset_choices = _get_dataset_choices()
_default_dataset = _dataset_choices[0] if _dataset_choices else None

with gr.Blocks(title="CCAR Backtesting Agent") as demo:

    gr.Markdown("# CCAR Backtesting Analysis Agent")

    # ── Dataset selector ──────────────────────────────────────────────────────
    with gr.Row():
        dataset_dropdown = gr.Dropdown(
            choices=_dataset_choices,
            value=_default_dataset,
            label="Dataset",
            scale=0,
            min_width=160,
        )

    # ── Main layout ───────────────────────────────────────────────────────────
    with gr.Row():

        # Left: summary dashboard (on load) / agent gallery (after first request)
        with gr.Column(scale=3):

            # MPE bar charts — visible by default
            summary_plot = gr.Plot(label="MPE by Statement Month", visible=True)

            # Average MPE table
            avg_mpe_table = gr.Dataframe(
                label="Average MPE Summary (all statement months)",
                visible=True, interactive=False, wrap=True,
            )

            # Negative predicted value alerts
            neg_pred_table = gr.Dataframe(
                label="⚠️ Statement Months with Negative Predicted Values",
                visible=True, interactive=False, wrap=True,
            )

            # AMPE > 5% alerts
            ampe_flag_table = gr.Dataframe(
                label="⚠️ Statement Months with AMPE > 5%",
                visible=True, interactive=False, wrap=True,
            )

            # Agent gallery — hidden until first request
            gallery = gr.Gallery(
                label="Generated Charts (newest first)",
                columns=2, height=560, object_fit="contain",
                show_label=True, visible=False,
            )
            refresh_btn = gr.Button("🔄 Refresh Gallery", size="sm", visible=False)

        # Right: chatbox
        with gr.Column(scale=2):
            chatbot = gr.Chatbot(label="Conversation", height=520)
            with gr.Row():
                msg_box = gr.Textbox(
                    placeholder="e.g. Show me Payment MPE by statement month at portfolio level…",
                    label="Your request", scale=5, lines=2, autofocus=True)
                with gr.Column(scale=1, min_width=120):
                    submit_btn = gr.Button("▶ Run", variant="primary")
                    clear_btn  = gr.Button("🗑 Clear")
            status_box = gr.Textbox(label="Status", interactive=False, lines=1)

            gr.Markdown("### Quick-start examples")
            for ex in EXAMPLES:
                gr.Button(ex[:90] + "…", size="sm").click(
                    fn=lambda e=ex: e, outputs=msg_box)

    with gr.Accordion("📁 Sample data file paths", open=False):
        gr.Markdown(f"""
Copy these paths into your requests:

| Round | Path |
|---|---|
| CCAR Round 1 | `{ROUND1_PATH}` |
| CCAR Round 2 | `{ROUND2_PATH}` |

Output charts saved to: `{os.path.abspath(OUTPUT_DIR)}`

Pre-computed summary CSV: `{DATA_INPUT_DIR}/{{dataset_name}}_summary.csv`
""")

    # ── Shared output list ────────────────────────────────────────────────────
    # Order must match return tuples in run_agent / clear_all / on_dataset_change
    _SUMMARY_OUTPUTS = [summary_plot, avg_mpe_table, neg_pred_table, ampe_flag_table]
    _RUN_OUTPUTS     = [chatbot, status_box, gallery, *_SUMMARY_OUTPUTS]

    # ── Events ────────────────────────────────────────────────────────────────

    def on_dataset_change(dataset_name):
        fig, avg_df, neg_df, ampe_df, history = _load_summary(dataset_name)
        return (
            *_show_summary(fig, avg_df, neg_df, ampe_df),  # summary components
            gr.update(visible=False),                        # gallery hidden
            gr.update(visible=False),                        # refresh_btn hidden
            history,                                         # chatbot
        )

    dataset_dropdown.change(
        fn=on_dataset_change,
        inputs=[dataset_dropdown],
        outputs=[*_SUMMARY_OUTPUTS, gallery, refresh_btn, chatbot],
    )

    submit_btn.click(
        fn=run_agent,
        inputs=[msg_box, chatbot, dataset_dropdown],
        outputs=_RUN_OUTPUTS,
    ).then(fn=lambda: "", outputs=msg_box)

    msg_box.submit(
        fn=run_agent,
        inputs=[msg_box, chatbot, dataset_dropdown],
        outputs=_RUN_OUTPUTS,
    ).then(fn=lambda: "", outputs=msg_box)

    clear_btn.click(
        fn=clear_all,
        inputs=[dataset_dropdown],
        outputs=_RUN_OUTPUTS,
    )

    refresh_btn.click(fn=_session_charts, outputs=gallery)

    demo.load(
        fn=_load_summary,
        inputs=[dataset_dropdown],
        outputs=[*_SUMMARY_OUTPUTS, chatbot],
    )


if __name__ == "__main__":
    import signal, subprocess, platform

    _PORT = int(os.environ.get("GRADIO_PORT", 7860))

    try:
        if platform.system() == "Darwin":
            result = subprocess.run(["lsof", "-ti", f"tcp:{_PORT}"], capture_output=True, text=True)
            for pid in result.stdout.strip().splitlines():
                try:
                    os.kill(int(pid), signal.SIGKILL)
                except Exception:
                    pass
        else:
            subprocess.run(["fuser", "-k", f"{_PORT}/tcp"], capture_output=True)
    except Exception:
        pass

    _jupyter_prefix = os.environ.get("JUPYTERHUB_SERVICE_PREFIX", "").rstrip("/")
    _root_path = f"{_jupyter_prefix}/proxy/{_PORT}" if _jupyter_prefix else ""

    demo.launch(
        server_port=_PORT,
        root_path=_root_path,
        share=False,
        inbrowser=False,
        theme=gr.themes.Soft(primary_hue="blue", neutral_hue="slate"),
    )
